apiVersion: v1
kind: PersistentVolume
metadata: 
  name: myebsvol1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-0a78d31de5adfe886   # copy ebs volume id give here
    fsType: ext4
