apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: mylivenessprobeurl
spec:
  containers: 
    - name: c00
      image: httpd
      ports:
        - containerPort: 80
      livenessProbe:
        initialDelaySeconds: 2
        periodSeconds: 5
        httpGet:       # HTTP url to check periodically
          path: /     # endpoint to check inside the container / means http://localhost/
          port: 80     #specific port to check

