apiVersion: v1
kind: Pod
metadata:
  name: nodelabels
  labels:                  # Specifies the label details uder it
    environment: Development
spec:
  containers:
    - name: resource
      image: ubuntu
      command: ["bin/bash", "-c", "while true; do echo resource; sleep 5; done"]
  nodeSelector:    # specifies which node to run the pod
     hardware: t2-medium
