apiVersion: v1
kind: Pod
metadata:
  name: labelspod
  labels:                  # Specifies the label details uder it
    myname: Mukesh
    environment: Development
spec:
  containers:
    - name: resource
      image: ubuntu
      command: ["bin/bash", "-c", "while true; do echo resource; sleep 5; done"]
