apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
    - name: resource
      image: centos
      command: ["bin/bash", "-c", "while true; do echo resource; sleep 5; done"]
      resources:             #Describes the type of resorces to be used
        requests:
          memory: "64Mi"            #<value in mebibyte>    A mebibyte is 1,048,576 bytes ex: 64 Mi
          cpu: "100m"           # CPU core split into 1000 units(milli=1000), ex:100m
        limits:
          memory: "128Mi"           #<value in mebibyte> ex:128Mi
          cpu: "200m"               #<value in milicores> ex:200m 
