kind: Pod
apiVersion: v1
metadata:
  name: testservice
  labels:
    myvalue: demo  # label for applying service later
spec:
  containers:
    - name: c00
      image: httpd
      ports: 
        - containerPort: 80
